### ISSUE TITLE
Add fade animation when loading a new fact

### ISSUE THREAD

**Issue by pierresaid** [pierresaid/random-cat-facts#3]
Add a fade animation when loading a new fact

**Comment by qwerty-rgb** [comment]
i am doing it

**Comment by qwerty-rgb** [comment]
sorry unable do it assign it to someone else and is up for grabs

**Comment by roycebradley** [comment]
@pierresaid Hey, I can work on this if it is still available. Would like to chat about what exactly you're looking for!

**Comment by mblaul** [comment]
@pierresaid @roycebradley I actually just created a PR for this, sorry I didn't claim beforehand. 😶
